# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-26 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleFinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=35)),
            ],
        ),
        migrations.RenameModel(
            old_name='People',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='first',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='last_name',
            new_name='last',
        ),
        migrations.AddField(
            model_name='skill',
            name='person',
            field=models.ManyToManyField(related_name='skill_set', to='peopleFinder.Person'),
        ),
    ]
