# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-26 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleFinder', '0002_auto_20170426_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='No Email Available', max_length=254),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
